apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: observability-appset
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/iamgauravpande/wsl2-microk8s-lab.git
      revision: main
      files:
      - path: "observability/tenant-discovery/tenant/**/config.json"
  template:
    metadata:
      name: '{{tenantid}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/iamgauravpande/wsl2-microk8s-lab.git
        targetRevision: main
        path: 'observability/tenants/{{tenantid}}'
        helm:
          valueFiles:
            - '{{tenantid}}.yaml'
      destination:
        server: '{{cluster.address}}'
        namespace: '{{cluster.namespace}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true